### ISSUE TITLE
Tord's todo list

### ISSUE THREAD

**Issue by SunyataZero** [MettaCenter/DailyMettaApp#1]

**Comment by SunyataZero** [comment]
* [ ] {iOS} Contacting people who have developed similar apps already: https://github.com/MettaCenter/DailyMettaApp/wiki/Similar-software-and-inspiration
* Does anyone have experience with iOS? Niharika?
* [x] Write ad for devs and send to Stephanie
* [x] Ask the devs from the previous project
  * [ ] Puneet
* [ ] Who has designed the metta center website? This person may be able to help us
* [ ] Who designed the iOS app [Easwaran’s Thought for the Day](https://itunes.apple.com/us/app/easwarans-thought-for-the-day/id568758085?mt=8)?
* [ ] [stackoverflow sidebar](http://meta.stackoverflow.com/questions/281524/open-source-advertising-sidebar-1h-2015) {We need to create graphics}
* [ ] Idealist.org
* [ ] **volonteermatch.org**
* [ ] Metta twitter
* [ ] Metta google plus
* [ ] Metta facebook
* [x] **[sourceforge](https://sourceforge.net/p/forge/helpwanted/programmers/thread/d90d7046/)** {*Active*}
* [ ] @SunyataZero: **Openhatch.org**
  * [ ] create an account and list ways people can help
    * [ ] change url (removing space) {email sent to support}
  * [ ] **People who can pitch in [php example search](https://openhatch.org/people/?q=can_pitch_in:%22php%22)**
  * [ ] [button on our homepage](http://blog.openhatch.org/2010/let-people-help-your-project-give-them-a-button-to-click/) {currently not working, [file bug](https://github.com/openhatch/oh-mainline/issues?q=is%3Aissue+is%3Aopen+%22want+to+help%22+) if this problem persist after change of url}
* [ ] **[Openhub](https://www.openhub.net/)**
* [ ] [dzone](http://dzone.com/)
* [ ] @SunyataZero: Contacting programming friends
* [ ] ***asking openly in #openhatch channel on freenode*** http://webchat.freenode.net/


More ideas:
* **Contacting [OFTC](http://www.oftc.net/)**
* peace movement
* open source movement
* search terms: promoting an open source project
* do a web search on what your project does and contact the developers
  * [commonsensemedia](https://www.commonsensemedia.org/learning-ratings) -> Discover by skill -> Emotions and social skills
  * Openhub - *has tags like non-violence, peace, empathy*
* alternativeto, openhub and other sites [link](http://alternativeto.net/software/ohloh/)


Skills we need:
* iOS

**Comment by SunyataZero** [comment]
#### Android icons

| Folder | Name | Usage | Notes |
| --- | --- | --- | --- |
| action | ic_event | Pick a date |  |
| action | ic_search | Search |  |
| navigation | ic_arrow_back | Instead of caret |  |
| toggle | ic_star | Favorite |  |
| social | ic_share | Sharing |  |

**Comment by SunyataZero** [comment]
##### Search in the action bar
- http://blog.lovelyhq.com/implementing-a-live-list-search-in-android-action-bar/
- http://developer.android.com/training/search/setup.html
- http://developer.android.com/guide/topics/search/search-dialog.html
- http://stackoverflow.com/questions/21585326/implementing-searchview-in-action-bar
- http://www.vogella.com/tutorials/AndroidActionBar/article.html

**Comment by SunyataZero** [comment]
http://stackoverflow.com/questions/18832890/android-nullpointerexception-on-searchview-in-action-bar
